% Change the size of the paper your CV will be printed on
% by entering either a4paper or letterpaper here.
\documentclass[a4paper]{Resume}

\usepackage[x11names]{xcolor}
% Set color of body text
\color{black}

\begin{document}
\SweaveOpts{concordance=TRUE}
	
% Set page colour using X11names colour definitions
\setPageColour{white}

% Set header details being aligned to the right or left
% If an image is displayed it will be shown on the
% opposite side to what is set here.
\setHeaderAlignment{left}

% Set colour of all headings, header highlights
\setHeadingColours{SlateGray3}

% Set image file to be displayed in header
% If left blank no image is displayed
%\setImage{profilepic.jpg}

% If image not being displayed then user can
% move contact details to opposite side of
% page to name and jobtitle.
% Use either opposite or below
\setContactLocation{opposite}

% Set up information needed for header.
% If you do not want to include certain
% information use {} instead. 
\setYourName{Patrick Harned}
\setYourJobTitle{Data Scientist/Machine Learning Engineer}
\setYourMobileNo{347-263-0441}
\setYourEmailAddr{pwharned@gmail.com}
\setYourWebAddr{pwharned.github.io}

% Display header information 
\showHeader

% Set up whether section headings are on the left or right
\setSectionAlignment{left}

% Creates a new section title / heading

\personalStatement{I am a Data Scientist and Machine Learning Engineer with a passion for NLP and performance computing.}

 \newHeading{}

% Add up to nine core skills. If they are
% all not needed use {} instead.
\begin{minipage}{.25\textwidth}
  \textcolor{\HeadingColour}{\robotoThin{\textbf{\large{Languages}}}}
  \vspace{1em}
  \begin{itemize}
  \item{Scala/Java}
  \item{Python}
  \item{C/C++}
  \item{Go}
  \item{Rust}
  
  \end{itemize}
\end{minipage}% This must go next to `\end{minipage}`
\begin{minipage}{.25\textwidth}
  \textcolor{\HeadingColour}{\robotoThin{\textbf{\large{Frameworks}}}}
  \vspace{1em}
    \begin{itemize}
  \item{Pandas/Sklearn}
  \item{Zio}
  \item{SparkMMLib}
  \item{PyTorch}
  \item{React}
  
  \end{itemize}
\end{minipage}% This must go next to `\end{minipage}`
\begin{minipage}{.25\textwidth}
  \textcolor{\HeadingColour}{\robotoThin{\textbf{\large{Platforms}}}}
  \vspace{1em}
    \begin{itemize}
  \item{Hadoop/Spark}
  \item{Kubernetes/Openshift}
  \item{AWS/GCP}
  \item{Linux}
  \item{Docker}
  
  \end{itemize}
\end{minipage}% This must go next to `\end{minipage}`
\begin{minipage}{.25\textwidth}
  \textcolor{\HeadingColour}{\robotoThin{\textbf{\large{Skills}}}}
  \vspace{1em}
    \begin{itemize}
  \item{Machine Learning}
  \item{Gen AI}
  \item{Analytics/Big Data}
  \item{NLP}
  \item{Embedded Systems}
  
  \end{itemize}
\end{minipage}


\newHeading{Career Summary}

% Set up whether job title or company printed first
% Either use JobFirst or CompanyFirst
\setJobCompanyOrder{JobFirst}

% This displays the whole of the role information
% including dates [1], job title [2],
% company name [3] and role summary [4]
% If a full history is required use \newrole and \roleAchievements
% If only a brief description needed then just use \newrole
\newRole{2019 -- present}
        {Data Scientist}
        {IBM Expert Labs}
        {Develop and deploy novel AI solutions.}
        \newline


\roleAchievements{Developed monitoring platform for LLM workloads on NVIDIA GPUs.}
{Develop and research novel techniques for improving computational efficiency of LLM training and inferencing. Develop high performance inferencing engine for LLMs.}
{Fine tune geospatial foundation models and Large Langage Models (LLMS) on proprietary data.}
{Develop high throuput C++ applications for performing embdedded database machine learning to support model drift and explainabilty analysis on federated data. }
{Develop federated data platform for tracking bias across machine learning models deployed to Google Cloud. }
{Research applicability of LLMs in machine translation. }



\newRole{2018 -- 2019}
{Data Specialist}
{Princeton University}
{Assist research team in producing visualizations, data validation and data quality pipelines, and conducting statistical analysis of Arab Barometer survey data.}

\roleAchievementsthree{Design and deploy data quality monitoring pipelines in R and Python. Build regression and RandomForest models to analyze survey data and contribute to original research. Perform statistical analysis and quality analysis of survey data. Provide Arabic-English translation assistance.}
{Build pipleines for cleanining and managing Arab Barometer survey data to support automated data cleaning.}
{Build dashboards, reporting and analytics pipelines. Conducted statistical analysis of Arab Barometer data and contributed to research.}


% move, duplicate, delete or comment out the following line if necessary
% This is training you have done in your own time


% School education
\newHeading{Education}
         
\newCourse{2019}{Dual Masters of Global Policy Studies and Middle Eastern Studies}{University of Texas at Austin}{}
\newCourse{2015}{Bachelors of Arts, Classical Langauges}{Hunter College, City University of New York}{}

\newHeading{Languages}
\addLanguages{Native English, Professional Fluency in Arabic,}
		  {Conversational  in Japanese,}
		  {German,}
		  {French and}
		  {Turkish}
          
\clearpage


 

\end{document}